require 'rake'
require 'active_record'
require 'logger'
require 'pg'
require 'sinatra/activerecord/rake'

ActiveRecord::Base.establish_connection(
  :adapter  => "postgresql",
  :host     => "localhost",
  :database => "flightlog",
  :username => "flightlog",
  :password => "flightlog"
)
